version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - goconst
    - gocyclo
    - misspell
    - revive
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    staticcheck:
      checks:
        ["all", "-QF1003", "-ST1003", "-QF1008", "-QF1006", "-QF1007", "-QF1001", "-ST1020"]
    # https://golangci-lint.run/usage/linters/#revive
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: true
          exclude: [""]
          arguments:
            - ["ID"] # AllowList
            - ["VM"] # DenyList
            - - upper-case-const: true
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/drakkan/sftpgo
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
