run:
  timeout: 5m
  issues-exit-code: 1
  tests: true


linters-settings:
  dupl:
    threshold: 150
  errcheck:
    check-type-assertions: false
    check-blank: false
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/drakkan/sftpgo
  #govet:
    # report about shadowed variables
    #check-shadowing: true
    #enable:
    #  - fieldalignment

linters:
  enable:
    - goconst
    - errcheck
    - gofmt
    - goimports
    - revive
    - unconvert
    - unparam
    - bodyclose
    - gocyclo
    - misspell
    - whitespace
    - dupl
    - rowserrcheck
    - dogsled