name: 🚀 Feature request
description: Suggest an idea for SFTPGo
labels: ["suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        ### 👍 Thank you for contributing to our project!
        Before asking for help please check our [support policy](https://github.com/drakkan/sftpgo?tab=readme-ov-file#support).
        If you are a [commercial user](https://sftpgo.com/) please contact us using the dedicated [email address](mailto:support@sftpgo.com).
        If you'd like to contribute code, please make sure to read and understand our [Contributor License Agreement (CLA)](https://sftpgo.com/cla.html).
        You’ll be asked to accept it when submitting a pull request.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: dropdown
    id: usecase
    attributes:
      label: What are you using SFTPGo for?
      description: We'd like to understand your SFTPGo usecase more
      multiple: true
      options:
        - "Private user, home usecase (home backup/VPS)"
        - "Professional user, 1 person business"
        - "Small business (3-person firm with file exchange?)"
        - "Medium business"
        - "Enterprise"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false