.nh
.TH "SFTPGO" "1" "Mar 2026" "SFTPGo 2.7.99-dev" "SFTPGo Manual"

.SH NAME
sftpgo - Full-featured and highly configurable file transfer server


.SH SYNOPSIS
\fBsftpgo [flags]\fP


.SH DESCRIPTION
Full-featured and highly configurable file transfer server


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for sftpgo

.PP
\fB-v\fP, \fB--version\fP[=false]


.SH SEE ALSO
\fBsftpgo-acme(1)\fP, \fBsftpgo-gen(1)\fP, \fBsftpgo-initprovider(1)\fP, \fBsftpgo-ping(1)\fP, \fBsftpgo-portable(1)\fP, \fBsftpgo-resetprovider(1)\fP, \fBsftpgo-resetpwd(1)\fP, \fBsftpgo-revertprovider(1)\fP, \fBsftpgo-serve(1)\fP, \fBsftpgo-smtptest(1)\fP
