.nh
.TH "SFTPGO-GEN-COMPLETION" "1" "Mar 2026" "SFTPGo 2.7.99-dev" "SFTPGo Manual"

.SH NAME
sftpgo-gen-completion - Generate the autocompletion script for the specified shell


.SH SYNOPSIS
\fBsftpgo gen completion [bash|zsh|fish|powershell] [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for sftpgo for the specified shell.

.PP
See each sub-command's help for details on how to use the generated script.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH SEE ALSO
\fBsftpgo-gen(1)\fP, \fBsftpgo-gen-completion-bash(1)\fP, \fBsftpgo-gen-completion-fish(1)\fP, \fBsftpgo-gen-completion-powershell(1)\fP, \fBsftpgo-gen-completion-zsh(1)\fP
