.nh
.TH "SFTPGO-ACME" "1" "Mar 2026" "SFTPGo 2.7.99-dev" "SFTPGo Manual"

.SH NAME
sftpgo-acme - Obtain TLS certificates from ACME-based CAs like Let's Encrypt


.SH SYNOPSIS
\fBsftpgo acme [flags]\fP


.SH DESCRIPTION
Obtain TLS certificates from ACME-based CAs like Let's Encrypt


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for acme


.SH SEE ALSO
\fBsftpgo(1)\fP, \fBsftpgo-acme-run(1)\fP
